# Form implementation generated from reading ui file 'ui/rov_gui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1244, 970)
        self.splitter = QtWidgets.QSplitter(parent=Dialog)
        self.splitter.setGeometry(QtCore.QRect(0, 0, 1041, 51))
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setObjectName("splitter")
        self.connect_state = QtWidgets.QLabel(parent=self.splitter)
        self.connect_state.setObjectName("connect_state")
        self.speed_state = QtWidgets.QLabel(parent=self.splitter)
        self.speed_state.setObjectName("speed_state")
        self.claw_label = QtWidgets.QLabel(parent=self.splitter)
        self.claw_label.setObjectName("claw_label")
        self.video = QtWidgets.QLabel(parent=Dialog)
        self.video.setGeometry(QtCore.QRect(10, 60, 1031, 881))
        self.video.setObjectName("video")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(1060, 250, 201, 491))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.temperature_slider = QtWidgets.QSlider(parent=self.horizontalLayoutWidget)
        self.temperature_slider.setStyleSheet("/* 1. 滑动槽（底部的灰色轨道） */\n"
"QSlider::groove:vertical {\n"
"    background: #e0e0e0;\n"
"    width: 24px; /* 这里决定了滑杆有多粗！你可以改大改小 */\n"
"    border-radius: 12px; /* 圆角，通常是宽度的一半 */\n"
"}\n"
"\n"
"/* 2. 已滑过的区域（代表当前数值的颜色带，比如变成显眼的绿色） */\n"
"QSlider::sub-page:vertical {\n"
"    background: #00B050; /* 咱们之前选的标准绿色 */\n"
"    width: 24px;\n"
"    border-radius: 12px;\n"
"}\n"
"\n"
"/* 3. 滑块手柄（你用鼠标拖动的那个小方块） */\n"
"QSlider::handle:vertical {\n"
"    height: 30px; /* 手柄的高度 */\n"
"    margin: 0px -4px; /* 让手柄往两边稍微凸出去一点，更好看 */\n"
"    background: white;\n"
"    border: 2px solid #00B050;\n"
"    border-radius: 15px;\n"
"}")
        self.temperature_slider.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.temperature_slider.setObjectName("temperature_slider")
        self.horizontalLayout.addWidget(self.temperature_slider)
        self.current_slider = QtWidgets.QSlider(parent=self.horizontalLayoutWidget)
        self.current_slider.setStyleSheet("/* 1. 滑动槽（底部的灰色轨道） */\n"
"QSlider::groove:vertical {\n"
"    background: #e0e0e0;\n"
"    width: 24px; /* 这里决定了滑杆有多粗！你可以改大改小 */\n"
"    border-radius: 12px; /* 圆角，通常是宽度的一半 */\n"
"}\n"
"\n"
"/* 2. 已滑过的区域（代表当前数值的颜色带，比如变成显眼的绿色） */\n"
"QSlider::sub-page:vertical {\n"
"    background: #00B050; /* 咱们之前选的标准绿色 */\n"
"    width: 24px;\n"
"    border-radius: 12px;\n"
"}\n"
"\n"
"/* 3. 滑块手柄（你用鼠标拖动的那个小方块） */\n"
"QSlider::handle:vertical {\n"
"    height: 30px; /* 手柄的高度 */\n"
"    margin: 0px -4px; /* 让手柄往两边稍微凸出去一点，更好看 */\n"
"    background: white;\n"
"    border: 2px solid #00B050;\n"
"    border-radius: 15px;\n"
"}")
        self.current_slider.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.current_slider.setObjectName("current_slider")
        self.horizontalLayout.addWidget(self.current_slider)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(1080, 750, 160, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.temperature_label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.temperature_label.setFont(font)
        self.temperature_label.setObjectName("temperature_label")
        self.horizontalLayout_2.addWidget(self.temperature_label)
        self.current_lable = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_2)
        self.current_lable.setObjectName("current_lable")
        self.horizontalLayout_2.addWidget(self.current_lable)
        self.splitter_2 = QtWidgets.QSplitter(parent=Dialog)
        self.splitter_2.setGeometry(QtCore.QRect(1060, 10, 181, 141))
        self.splitter_2.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.temperature = QtWidgets.QLabel(parent=self.splitter_2)
        self.temperature.setObjectName("temperature")
        self.current = QtWidgets.QLabel(parent=self.splitter_2)
        self.current.setObjectName("current")
        self.current_state = QtWidgets.QLabel(parent=self.splitter_2)
        self.current_state.setObjectName("current_state")
        self.over_time = QtWidgets.QLabel(parent=self.splitter_2)
        self.over_time.setObjectName("over_time")
        self.refresh_button = QtWidgets.QPushButton(parent=self.splitter_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.refresh_button.setFont(font)
        self.refresh_button.setObjectName("refresh_button")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.connect_state.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">手柄未连接</span></p></body></html>"))
        self.speed_state.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Speed state: SLOW</span></p></body></html>"))
        self.claw_label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">claw open</span></p></body></html>"))
        self.video.setText(_translate("Dialog", "TextLabel"))
        self.temperature_label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">温度</p></body></html>"))
        self.current_lable.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">电流</span></p></body></html>"))
        self.temperature.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">温度: 20.0</span>℃</p></body></html>"))
        self.current.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">电机电流: 1.2A</span></p></body></html>"))
        self.current_state.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">未过流</span></p></body></html>"))
        self.over_time.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">过流时间: 0 min 0s</span></p></body></html>"))
        self.refresh_button.setText(_translate("Dialog", "刷新"))
