; ---键盘映射（wok第一次搞有点激动呢ovo)---
; 所以这些东西算是键值对？
[keyboard]
key_forward = W
key_backward = S
key_yaw_left = A 
key_yaw_right = D 
key_left = LEFT  
key_right = RIGHT  
key_up = UP
key_down = DOWN
key_mode_toggle = X
key_claw_open = Q
key_claw_close = E

; --- 手柄轴映射ovo ---
[axis]
y = 1
yaw = 0
x = 2
z = 3
[button]
X = 3
LB = 6
RB = 7
[x]
max = 1
axis = 2
deadzone = 0.05
[y]
max = 1
axis = 1
deadzone = 0.05
[z]
max = 1
axis = 3
deadzone = 0.05
[yaw]
max = 1
axis = 0
deadzone = 0.05
; --- 速度档位 ---
[speed_modes]
mode0_name = SLOW
mode0_rate = 0.3
mode0_color = #00B050
mode1_name = MEDIUM
mode1_rate = 0.6
mode1_color = #FFA500
mode2_name = FAST
mode2_rate = 1
mode2_color = #FF0000
; --- 过流保护阈值 ---
[overcurrent]
threshold = 10.0